baseURL = 'https://documentation.donaldjenkins.com/'
languageCode = 'en-us'
title = 'Documentation'
theme = "hugo-book"

# Book configuration
disablePathToLower = true
enableGitInfo = true
disableKinds = ['RSS', 'robotsTXT', 'taxonomy', 'term']

[params]
  BookTheme = 'auto'
  BookLogo = 'icon-192.png'
  BookRepo = 'https://github.com/donaldjenkins/documentation'
  BookCommitPath = 'commit'
  BookComments = false

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

  [menu]
  # [[menu.before]]
  [[menu.after]]
    name = "Release notes"
    url = "https://github.com/donaldjenkins/documentation/releases/"
    weight = 2

  # [[menu.before]]
  [[menu.after]]
    name = "Home"
    url = "https://www.donaldjenkins.com/"
    weight = 2

  [[menu.after]]
    name = "Contact"
    url = "https://www.donaldjenkins.com/contact"
    weight = 3
